### PR TITLE
Issue 682

### PR DESCRIPTION
**Pull request by danielgerlag**
- Addresses #682 
- Adds ability to schedule execution pointers dependent another pointer completing first
- When compensating multiple steps, preserves reverse order of failed steps for compensating steps

### CODE REVIEW

**Comment by danielgerlag** [comment]
@MrZoidberg

**Comment by MrZoidberg** [comment]
@danielgerlag cool, thank you so much, man!

**Comment by MrZoidberg** [comment]
@danielgerlag Hi! Could you please do a release with this bug fix?

**Comment by danielgerlag** [comment]
It should've been deployed last week... is it not working?

**Comment by MrZoidberg** [comment]
@danielgerlag there is no release with the bug fix

**Comment by danielgerlag** [comment]
@MrZoidberg did you try this one? https://www.nuget.org/packages/WorkflowCore/3.3.2

**Comment by MrZoidberg** [comment]
No, sorry, I was expecting to see a release on Github. Thanks

**Pull request merged**
