### PR TITLE
Allow dependency injection on Workflow

### PR DESCRIPTION
**Pull request by glucaci**
It will be very usefull to can inject services/configuration into Workflow directly.

Example:
```csharp
public class SampleWorkflow : IWorkflow<SampleRequest>
{
    private readonly IOptions<WorkflowOptions> _options;

    public SampleWorkflow(IOptions<WorkflowOptions> options)
    {
        _options = options;
    }

    public string Id => nameof(SampleWorkflow);

    public int Version => 1;

    public void Build(IWorkflowBuilder<SampleRequest> builder)
    {
        builder
            .StartWith(context => ExecutionResult.Next())
            .Then<SampleStep>()
                .Input(step => step.Request, data => data)
                .OnError(WorkflowErrorHandling.Retry, _options.Value.RetryInterval);
    }
}
```

### CODE REVIEW

**Comment by vaclavpfeifer** [comment]
I think it is already possible to register a WF using DI. 
RegisterWorkflow(serviceProvider.GetService<SomeDiRegisteredWf>());

**Comment by glucaci** [comment]
Where is this method?
These are the only two methods of ```RegisterWorkflow```
```csharp
public interface IWorkflowController
{
    ...
    void RegisterWorkflow<TWorkflow>() where TWorkflow : IWorkflow, new();

    void RegisterWorkflow<TWorkflow, TData>()
      where TWorkflow : IWorkflow<TData>, new()
      where TData : new();
    ...
}
```

**Comment by glucaci** [comment]
Ok, I saw... you mean on the ```IWorkflowRegistry```.
We used till now the IWorkflowHost to register the workflows because you need also to start it afterwards. It's pretty confusing registering workflows because this method is everywhere, IWorkflowHost , IWorkflowController, IWorkflowRegistry

**Comment by glucaci** [comment]
The solution from ```IWorkflowRegistry``` implies that you have to ```new````manually the Workflow which is not very clean, because using the ```IServiceProvider``` is not an option

**Comment by glucaci** [comment]
@danielgerlag what do you think? could we merge this?

**Comment by glucaci** [comment]
Done.
Only Core right? Why are you not using same version for all the packages?

**Comment by danielgerlag** [comment]
We use the same major version, but allow the minor and patch to vary.

**Comment by IvanJosipovic** [comment]
@danielgerlag Do you have an ETA when this code will be released?

Thank you!

**Comment by danielgerlag** [comment]
ah, it looks like it didn't deploy because the `PackageVersion` was not incremented, I'll sort that out!

**Pull request merged**
