### PR TITLE
Lock each list of memory persistence before using

### PR DESCRIPTION
**Pull request by qazq**
In some cases, add/remove workflow at persistence store will throw an
exception. ("Collection was modified; enumeration operation may not execute.")

### CODE REVIEW

**Comment by danielgerlag** [comment]
Which persistence provider are you using?

**Comment by qazq** [comment]
MemoryPersistenceProvider

**Comment by qazq** [comment]
This is my testing code.
```cs
            var host = serviceProvider.GetService<IWorkflowHost>();
            host.RegisterWorkflow<HelloWorldWorkflow>();        
            host.Start();

            Thread.Sleep(100);
            for (int i = 0; i < 100; i++)
            {
                host.StartWorkflow("HelloWorld", 1, null);
                if (i % 10 == 0)
                {
                    Thread.Sleep(1000);
                }
            }
```

It has the chance to happen the exception.

**Comment by qazq** [comment]
ConcurrentBag<> seems cannot remove a specific item, so I add the locks.

**Pull request merged**
