### PR TITLE
Update WorkflowHost.cs

### PR DESCRIPTION
**Pull request by perezsebas**
Method added to get the current state of the protected _shutdown property

### CODE REVIEW

**Comment by danielgerlag** [comment]
What's your use case for this?

**Comment by perezsebas** [comment]
Hello, thank you for your reply. I am trying to run two workflows, one after the other but I am getting an exception ("Operation is not valid due to the current state of the object.") because when runnning the first one I need to execute workflowHost.Start() but when running the second one when the execution reaches this line of code it throwns this exception.

I saw this property called _shutdown that starts false and then turns true when workflowHost.Start() was executed. So the idea is to have a conditional to check if _shutdown equals true then don't run again workflowHost.Start(). The only problem is _shutdown property is protected so I can't access it, that's why I added this method to be able to get its value.

**Comment by germandb** [comment]
The WorkflowHost.Start() only needs to be invoke once when you start your service. You dont need to start the Host for each Workflow. Please take a look into [Using WorkflowCore with ASP.NET.Core](https://github.com/danielgerlag/workflow-core/wiki/97.-Using-with-ASP.NET-Core)

**Comment by danielgerlag** [comment]
yup, the intended usage is to start the host when you app starts and leave it started as it runs internal worker pools.

**Comment by perezsebas** [comment]
Thank you guys for your help, it is working like you said, have a nice week.

**Pull request closed without merging**
