### PR TITLE
fix adding a key to dictionary in thread unsafe manner

### PR DESCRIPTION
**Pull request by georgebratu**
Hi ! Once in a while, we were getting an error "the same key was already added" in the QueueConsumer.cs It seems that the adding a key in the dictionary was not written to be thread safe. So this pull request fixes this concurrency issue. So the only change is that before trying to add "item" in key in "_activeTasks" check inside the lock if it's already added. If it's not the carry on, otherwise, go back to the initial check.

### CODE REVIEW

**Comment by georgebratu** [comment]
Any thoughts on this ? Do you need more information ?

**Review by danielgerlag — COMMENTED** [review]
What about just using `ConcurrentDictionary` from `System.Collections.Concurrent`?

**Comment by danielgerlag** [comment]
I believe this issue was fixed in a previous release

**Comment by georgebratu** [comment]
Sorry about late reply, using ConcurrentDictionary didnt fix it. It's clear that the code is not thead safe if you dont implement the double check properly.
You are doing:

```
lock (_activeTasks)
                    {
                        hasTask = _activeTasks.ContainsKey(item);
                    }

......... some code here .....

lock (_activeTasks)
                    {
                        _activeTasks.Add(item, waitHandle);
                    }
```

So when you add the item in activeTasks it was already added in another thread.
That's why I inserted a check before adding the key like:

```
checkAgainTheDictionary:
lock (_activeTasks)
                    {
                        hasTask = _activeTasks.ContainsKey(item);
                    }

......... some code here .....

lock (_activeTasks)
                    {
                        if (_activeTasks.ContainsKey(item))
                            goto checkAgainTheDictionary;
                        _activeTasks.Add(item, waitHandle);
                    }
```

You ALWAYS need to check inside the lock block if the key already exists before adding in order to do proper thread safe code.

**Comment by danielgerlag** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/lock-statement

**Pull request closed without merging**
