### PR TITLE
Don't mark an event as processed when there are no subscriptions

### PR DESCRIPTION
**Pull request by MrZoidberg**
Mostly fixes issue #773

### CODE REVIEW

**Comment by danielgerlag** [comment]
What about setting the effective datetime of the `WaitFor` to an earlier time?

**Comment by MrZoidberg** [comment]
@danielgerlag I'm not using time in WaitFor, so it is set to minimal time

**Comment by danielgerlag** [comment]
In your example you have
```c#
public void Build(IWorkflowBuilder<MyDataClass> builder)
            {
                builder
                    .StartWith(context => ExecutionResult.Next())
                    .WaitFor("MyEvent", data => data.Value1.ToString(), data => DateTime.Now)
                    .Output(data => data.Value2, step => step.EventData)
                    .Then(context => ExecutionResult.Next())
                    .Output(data => data.Value3, step => "OK");
            }
```
What if you used

.WaitFor("MyEvent", data => data.Value1.ToString(), data => **DateTime.MinValue**)

**Comment by MrZoidberg** [comment]
@danielgerlag I see. I won't help because the EventConsumer is executed when there are no subscriptions yet, so the time there doesn't matter.

**Comment by danielgerlag** [comment]
@MrZoidberg we marked older events as unprocessed again when creating back dated subscriptions
see: https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Services/BackgroundTasks/WorkflowConsumer.cs#L95

**Comment by MrZoidberg** [comment]
@danielgerlag please check the test, it doesn't work with `.WaitFor("MyEvent", data => data.Value1.ToString(), data => DateTime.MinValue)`. Maybe I'm missing something, but in my real app I always use `DateTime.MinValue` and with the real scenario sending an event to Kafka and receiving a response very quickly the event is marked as processed and is never marked as unprocessed again. btw in the Workflow consumer, there is no lock for the event, so maybe the problem is that event is marked as processed after it is marked as unprocessed, what do you think?

**Comment by unaizorrilla** [comment]
We are experimenting the same kind of issue!

**Comment by MrZoidberg** [comment]
@danielgerlag hey. just checking if we can continue the discussion on this topic. I'm using a fork due to this issue and would love to help you to fix it.

**Comment by VKAlwaysWin** [comment]
@danielgerlag one note here that there are no locking on event by event Id here - https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Services/BackgroundTasks/WorkflowConsumer.cs#L94 which may lead to unexpected behaviour. Maybe it is worth to add something like this: https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Services/BackgroundTasks/EventConsumer.cs#L36 .

**Comment by MrZoidberg** [comment]
Closing my PR in flavor of #851

**Pull request closed without merging**
