### PR TITLE
Remove redundant dependency on Npgsql.EntityFrameworkCore.PostgreSQL.Design

### LINKED ISSUE #415: WorkflowCore.Persistence.PostgreSQL doesn't allow to use AutoMapper
**Stack trace**:
```
System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types.
Could not load type 'Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalFullAnnotationNames' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=2.2.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at AutoMapper.Configuration.MapperConfigurationExpression.AddMapsCore(IEnumerable`1 assembliesToScan) in C:\projects\automapper\src\AutoMapper\Configuration\MapperConfigurationExpression.cs:line 81
   at DP.Smev.UnitTests.Services.Rpf.Pension.Handlers.RpfResponseJsonExtractorTests.<>c.<.ctor>b__4_0(IMapperConfigurationExpression cfg) in C:\Users\nkirsanov\DigitalProfile\smev\test\DP.Smev.UnitTests\Services\Rpf\Pension\Handlers\RpfResponseJsonConstructorTests.cs:line 27
   at AutoMapper.MapperConfiguration.Build(Action`1 configure) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 288
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 60
   at DP.Smev.UnitTests.Services.Rpf.Pension.Handlers.RpfResponseJsonExtractorTests..ctor() in C:\Users\nkirsanov\DigitalProfile\smev\test\DP.Smev.UnitTests\Services\Rpf\Pension\Handlers\RpfResponseJsonConstructorTests.cs:line 26
```

The reason to this is the package depends on Npgsql.EntityFrameworkCore.PostgreSQL.Design, which depends on Microsoft.EntityFrameworkCore.Relational.Design which, according to [this issue](https://github.com/aspnet/EntityFrameworkCore/issues/10759) and my own little experiments, is the source of the problem for AutoMapper.

**Proposal for solution**: get rid of this dependency which tries to use some deprecated code.

### PR DESCRIPTION
**Pull request by kirsanium**
Closes #415

### CODE REVIEW

**Comment by kirsanium** [comment]
Some weird errors in CI tho.

**Comment by danielgerlag** [comment]
Looks like AppVeyor have changed something in their Ubuntu images which is causing the build to fail... I have opened a ticket with them

**Comment by danielgerlag** [comment]
The build should be working now

**Comment by kirsanium** [comment]
How do I restart the pipeline or do you do it?

**Comment by kirsanium** [comment]
I think it's ready to merge

**Comment by kirsanium** [comment]
Ready to merge!

**Comment by kirsanium** [comment]
@danielgerlag Hey, I would appreciate much if you merge this, this pull request is really needed.

**Pull request merged**
