### PR TITLE
Abstracted IWorkflowStep to allow generic builder extensions

### PR DESCRIPTION
**Pull request by igor-betin**
This is to be able to write extension methods for IStepBuilder<DynamicData, IStepBody>
Where I don't care about exact type of previous step

### CODE REVIEW

**Comment by danielgerlag** [comment]
I'm not sure I follow the problem this is solving

**Comment by igor-betin** [comment]
It's to allow user's own chaining methods, and to remove those from class implementation to extension methods

**Comment by danielgerlag** [comment]
Why does it need to be an interface for extension methods?

**Comment by igor-betin** [comment]
Because only interfaces can have generic type constraint, so the extension methods can be used with other TStepBody descendands in <out TStepBody>

**Comment by danielgerlag** [comment]
Could you include some examples of how this would be used?

**Comment by igor-betin** [comment]
I have abandoned attempts to make this engine work from json definitions and with full steps status reports with connection to the definition, but here is a snippet from an old branch.

In any case, all properties used by your builder implementation are public, no sense to keep them as instance methods

using System;
using System.Threading.Tasks;
using WorkflowCore.Interface;
using WorkflowCore.Models;
using WorkflowCore.Services;

namespace Deloitte.WorkflowCore.Extensions
{
    public static class StepBuilderExtensions
    {
        public static IStepBuilder<TData, DynamicActionStepBody> ThenAsync<TData, TPrevBody>(
            this IStepBuilder<TData, TPrevBody> self,
            Func<IStepExecutionContext, DynamicData, Task> bodyAsync)
            where TPrevBody : IStepBody
        {
            return self.ThenAsync(null, bodyAsync);
        }

        public static IStepBuilder<TData, DynamicActionStepBody> ThenAsync<TData, TPrevBody>(
            this IStepBuilder<TData, TPrevBody> self,
            object dataObject,
            Func<IStepExecutionContext, DynamicData, Task> bodyAsync) 
            where TPrevBody : IStepBody
        {
            var newStep = new WorkflowStep<DynamicActionStepBody>();
            self.WorkflowBuilder.AddStep(newStep);
            var stepBuilder = new StepBuilder<TData, DynamicActionStepBody>(self.WorkflowBuilder, newStep);
            stepBuilder.Input(x => x.BodyAsync, x => bodyAsync);
            if (dataObject != null)
                stepBuilder.Input(s => s.Object, w => dataObject);
            self.Step.Outcomes.Add(new StepOutcome() { NextStep = newStep.Id });
            return stepBuilder;
        }
        
        public static IStepBuilder<TData, DynamicActionStepBody> StartWithTitle<TData>(this IWorkflowBuilder<TData> self, string title, object dataObject = null)
        {
            var newStep = new WorkflowStep<DynamicActionStepBody>();
            self.AddStep(newStep);
            var stepBuilder = new StepBuilder<TData, DynamicActionStepBody>(self, newStep);
            stepBuilder.Input(s => s.Title, w => title);
            if (dataObject != null)
                stepBuilder.Input(s => s.Object, w => dataObject);
            
            return stepBuilder;
        }
    }
}

**Pull request closed without merging**
