### PR TITLE
Minor bug repairs

### PR DESCRIPTION
**Pull request by ccpony**
(1) fix take parameter to produce output even if take == 0
(2) fix CreateTime to reflect proper time (was producing default value of 01/01/0001).

### CODE REVIEW

**Comment by ccpony** [comment]
Jury duty this week.  Will complete this over the weekend.  Sorry for the delay.

**Comment by ccpony** [comment]
completed.

**Comment by danielgerlag** [comment]
What happened?

**Comment by ccpony** [comment]
Ugh.  I completed the bug fixes.  I'm guessing that I should have taken another step before closing.  Please excuse my inexperience in GitHub, Daniel.

**Comment by ccpony** [comment]
Please bear with me as I get up to speed on GitHub. I completed the fixes and set the status to complete.  I’m guessing that I missed a step in there.  My apologies.

**Comment by danielgerlag** [comment]
No worries, I really appreciate your participation, I will reopen and merge it tomorrow.  What is your real name btw? Can you add me on LinkedIn, I'd like to learn more about the project you are using this library for.

**Comment by ccpony** [comment]
Jeff Michelson.  I’ll add you on LinkedIn.  You’ll find the project that I’m developing to be an ideal fit for your tool.

Thanks.

**Pull request closed without merging**
