### PR TITLE
ActivityName as expression. It solves #542 issue. (Activity Compound Key)

### PR DESCRIPTION
**Pull request by alimozdemir**
**Describe the change**
The event type of `Activity` only requires a name which is equal to `eventKey` of `WaitFor`. Currently, the name is just a value. In that case, when an activity enqueued the first activity will be processed (`GetFirstOpenSubscription`). 

The PR includes an overload method for `Activity`. Allows the developer the customize their `eventKey` for activities. In the `Sample20`, I changed the activityName to a compound key. (e.g. `get-approval` to `get-approval-{workflowId}`)

The issue #542 will be fixed with this PR.

**Describe your implementation or design**
How did you go about implementing the change?

Only added an overload method for `Activity` with `Expression<Func<TData, IStepExecutionContext, string>> activityName`.

**Tests**
Did you cover your changes with tests?
*Yes*

**Breaking change**
Do you changes break compatibility with previous versions?
*No*

**Additional context**
Any additional information you'd like to provide?
*No*

### CODE REVIEW

**Comment by sunilsoniudaipur** [comment]
Sometimes if we can write  like this it is also works

`.Activity("",data=>DateTime.Now)
  .Input(step=>step.ActivityName, data=>data.UniqueId)
  Input(step=>step.EffectiveDate,data=>DateTime.Now)
`

**Review by danielgerlag — APPROVED** [review]

**Comment by lyzerk** [comment]
The PR build keep failing due to tests. (1 hour limit). Should I do something about it ?

**Comment by MathSee** [comment]
Is this change published on the last current nuget package available? (v3.5.1)

**Comment by danielgerlag** [comment]
No, we cannot merge until the tests are passing.

**Comment by lyzerk** [comment]
@danielgerlag  The tests are failing due to **time limit**. I asked a question, it is not too hard to reply. **Can I do something about it ?** If you could answer the question, I would like to merge the PR.

**Comment by MathSee** [comment]
@danielgerlag please give it a look to the PR #864. It's an another proposal solution for the #542 issue.

**Comment by danielgerlag** [comment]
@lyzerk The tests run fine on the master branch, so something has changed that is breaking them, you would need to debug them on your branch.

**Comment by lyzerk** [comment]
@danielgerlag  I have added a new test scenario. Therefore, it could increase the total execution time. I will remove the test scenario today.

**Pull request merged**
