### PR TITLE
Update EFCore to 7

### PR DESCRIPTION
**Pull request by elexisvenator**
**Describe the change**
Change all .net 6 package references to entity framework to 7.*.

**Describe your implementation or design**
How did you go about implementing the change?

**Tests**
All current tests pass, there shouldnt be a need for new tests.

**Breaking change**
This is NOT backwards compatible with EF core 6 or lower.

**Additional context**
This is a PR that will address #1128 , however there should be discussion about if this is the right approach, or if another way should be done to maintain compatibility with EFCore 6, such as creating a separate package.

### CODE REVIEW

**Comment by ErikEJ** [comment]
Why do you need this change?

**Comment by elexisvenator** [comment]
Our application makes used of libraries that require Npgsql 7.0.0+. (The library in question is [Marten 6.0](https://martendb.io/)). The earliest version of EntityFramework Core that supports this version of Npgsql is also 7.0.0+. There are also breaking changes in EntityFramework Core that means manually pinning the versions to 7 do not work (see #1128).

**Comment by ssougnez** [comment]
Up for this one?

I tried starting a new .NET 7 application with WorkflowCore and it does not work because of https://github.com/danielgerlag/workflow-core/issues/1128

**Comment by danielgerlag** [comment]
Sorry for the delay. I will get this one through in the next day or two.

**Pull request merged**
