### PR TITLE
Add context to If When ForEach and UserTask

### PR DESCRIPTION
**Pull request by IvanJosipovic**
**Describe the change**
Added new overloads for If/When/ForEach and UserTask with IStepExecutionContext

This allow using these tasks within a loop.

Solves: #599,#338

**Describe your implementation or design**
I copy/pasted the existing implementations and added IStepExecutionContext to the parameters.

**Tests**
No, let me know if they're needed.

**Breaking change**
No

**Additional context**
No

### CODE REVIEW

**Comment by IvanJosipovic** [comment]
@danielgerlag, could you please review this PR?

**Review by danielgerlag — APPROVED** [review]

**Comment by ChrisBertrand** [comment]
@IvanJosipovic can we get this merged?

**Comment by IvanJosipovic** [comment]
> @IvanJosipovic can we get this merged?

I don't have those super powers :p

**Comment by danielgerlag** [comment]
Yes, travelling at the moment. Will try this weekend.

**Pull request merged**
