### PR TITLE
Updated the Pomelo library to 3.1.0 to make it compatible with Entity…

### PR DESCRIPTION
**Pull request by paulose**
…Framework.Core 3.1.0 and bumped the WorkflowCore.Persistence.MySQL version to 1.2.2

### CODE REVIEW

**Comment by paulose** [comment]
No. It does not need a new migration. I have tested this on my local with the existing migration and submitted a new workflow and it worked.

**Comment by paulose** [comment]
Is there any other check you would like me to perform?

**Comment by danielgerlag** [comment]
The MySQL provider doesn't have the latest 2 migrations that all the other EF providers have.
Some of the new features may not work,

**Comment by danielgerlag** [comment]
updated in another PR

**Pull request closed without merging**
